### ISSUE TITLE
Epic: Deployment examples

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma-examples#4792]
- [ ] Create or update the deployment starter examples
	- [ ] Azure Functions
	- [x] prisma/docs#5087
	- [x] prisma/docs#5291
	- [x] prisma/docs#5109
	- [x] prisma/prisma-examples#4799
	- [x] prisma/docs#5088
	- [ ] Cloudflare Workers
	- [ ] Deno Deploy
	- [ ] Google Cloud functions
- [ ] Remove Heroku example guides (dependent on https://github.com/prisma/docs/issues/4843)

**Comment by jharrell** [comment]
Closing this as duplicate of prisma/prisma-examples#4721 

Moved all info over there.
